services:
  - type: web
    name: porquim-ia
    env: node
    plan: free
    buildCommand: PUPPETEER_CACHE_DIR=/opt/render/.cache/puppeteer npx puppeteer browsers install chrome && npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
